/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Sites
     * @description List sites, oldest first.
     *
     *     Args:
     *         service: The site service for this request.
     *         params: The requested collection window.
     *         site_status: Optional ``status`` filter from the query string.
     *
     *     Returns:
     *         The paginated envelope, ordered by ``created_at ASC, id ASC``.
     */
    get: operations["list_sites_api_v1_sites_get"];
    put?: never;
    /**
     * Create Site
     * @description Register a site.
     *
     *     Args:
     *         payload: The site to create.
     *         service: The site service for this request.
     *
     *     Returns:
     *         The created site, with HTTP 201.
     */
    post: operations["create_site_api_v1_sites_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sites/{site_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Site
     * @description Read one site, archived ones included.
     *
     *     Args:
     *         site_id: Identifier of the site to read.
     *         service: The site service for this request.
     *
     *     Returns:
     *         The requested site.
     */
    get: operations["get_site_api_v1_sites__site_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Site
     * @description Update a site's name, timezone or status.
     *
     *     Args:
     *         site_id: Identifier of the site to update.
     *         payload: The fields to change.
     *         service: The site service for this request.
     *
     *     Returns:
     *         The updated site.
     */
    patch: operations["update_site_api_v1_sites__site_id__patch"];
    trace?: never;
  };
  "/api/v1/facilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Facilities
     * @description List facilities, oldest first.
     *
     *     Args:
     *         service: The facility service for this request.
     *         params: The requested collection window.
     *         site_id: Optional ``site_id`` filter from the query string.
     *         facility_type: Optional ``facility_type`` filter from the query string.
     *         facility_status: Optional ``status`` filter from the query string.
     *
     *     Returns:
     *         The paginated envelope, ordered by ``created_at ASC, id ASC``.
     */
    get: operations["list_facilities_api_v1_facilities_get"];
    put?: never;
    /**
     * Create Facility
     * @description Register a facility inside a site.
     *
     *     Args:
     *         payload: The facility to create.
     *         service: The facility service for this request.
     *
     *     Returns:
     *         The created facility, with HTTP 201.
     */
    post: operations["create_facility_api_v1_facilities_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/facilities/{facility_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Facility
     * @description Read one facility, archived ones included.
     *
     *     Args:
     *         facility_id: Identifier of the facility to read.
     *         service: The facility service for this request.
     *
     *     Returns:
     *         The requested facility.
     */
    get: operations["get_facility_api_v1_facilities__facility_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Facility
     * @description Update a facility's name, type or status.
     *
     *     Args:
     *         facility_id: Identifier of the facility to update.
     *         payload: The fields to change.
     *         service: The facility service for this request.
     *
     *     Returns:
     *         The updated facility.
     */
    patch: operations["update_facility_api_v1_facilities__facility_id__patch"];
    trace?: never;
  };
  "/api/v1/facilities/{facility_id}/configuration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Facility Configuration
     * @description Read a facility's whole configuration in one request.
     *
     *     The facility, its site, its zones with their composition and its points with
     *     their last known state, assembled from a fixed number of queries.
     *
     *     Args:
     *         facility_id: Identifier of the facility to describe.
     *         service: The configuration read service for this request.
     *         include_archived: Whether archived zones and points are kept in the
     *             document; they are left out by default.
     *
     *     Returns:
     *         The configuration document.
     */
    get: operations["get_facility_configuration_api_v1_facilities__facility_id__configuration_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/control-zones": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Control Zones
     * @description List control zones, oldest first.
     *
     *     Args:
     *         service: The control zone service for this request.
     *         params: The requested collection window.
     *         facility_id: Optional ``facility_id`` filter from the query string.
     *         zone_type: Optional ``zone_type`` filter from the query string.
     *         zone_status: Optional ``status`` filter from the query string.
     *
     *     Returns:
     *         The paginated envelope, ordered by ``created_at ASC, id ASC``.
     */
    get: operations["list_control_zones_api_v1_control_zones_get"];
    put?: never;
    /**
     * Create Control Zone
     * @description Register a control zone inside a facility.
     *
     *     Args:
     *         payload: The zone to create.
     *         service: The control zone service for this request.
     *
     *     Returns:
     *         The created zone, with HTTP 201.
     */
    post: operations["create_control_zone_api_v1_control_zones_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/control-zones/{zone_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Control Zone
     * @description Read one control zone, archived ones included.
     *
     *     Args:
     *         zone_id: Identifier of the zone to read.
     *         service: The control zone service for this request.
     *
     *     Returns:
     *         The requested zone.
     */
    get: operations["get_control_zone_api_v1_control_zones__zone_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Control Zone
     * @description Update a control zone's name, type or status.
     *
     *     Args:
     *         zone_id: Identifier of the zone to update.
     *         payload: The fields to change.
     *         service: The control zone service for this request.
     *
     *     Returns:
     *         The updated zone.
     */
    patch: operations["update_control_zone_api_v1_control_zones__zone_id__patch"];
    trace?: never;
  };
  "/api/v1/control-zones/{zone_id}/points": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Zone Point Assignments
     * @description List a control zone's composition, oldest assignment first.
     *
     *     Args:
     *         zone_id: Identifier of the zone whose composition to read.
     *         service: The assignment service for this request.
     *         params: The requested collection window.
     *
     *     Returns:
     *         The paginated envelope, ordered by ``created_at ASC, id ASC``.
     */
    get: operations["list_zone_point_assignments_api_v1_control_zones__zone_id__points_get"];
    put?: never;
    /**
     * Create Zone Point Assignment
     * @description Assign a point to a control zone under one role.
     *
     *     Args:
     *         zone_id: Identifier of the zone to assign the point to.
     *         payload: The point and the role it plays in the zone.
     *         service: The assignment service for this request.
     *
     *     Returns:
     *         The created assignment enriched with the point's metadata, with
     *         HTTP 201.
     */
    post: operations["create_zone_point_assignment_api_v1_control_zones__zone_id__points_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/control-zones/{zone_id}/points/{assignment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Zone Point Assignment
     * @description Remove one point from a control zone's composition.
     *
     *     The point itself is untouched; only the link is removed. This is the one
     *     real delete in the domain, and it is allowed precisely because an
     *     assignment carries no history worth keeping.
     *
     *     Args:
     *         zone_id: Identifier of the zone to remove the point from.
     *         assignment_id: Identifier of the assignment to remove.
     *         service: The assignment service for this request.
     *
     *     Returns:
     *         An empty response with HTTP 204.
     */
    delete: operations["delete_zone_point_assignment_api_v1_control_zones__zone_id__points__assignment_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/points": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Points
     * @description List points, oldest first.
     *
     *     Args:
     *         service: The point service for this request.
     *         params: The requested collection window.
     *         site_id: Optional ``site_id`` filter from the query string.
     *         facility_id: Optional ``facility_id`` filter from the query string.
     *         point_kind: Optional ``point_kind`` filter from the query string.
     *         metric_type: Optional ``metric_type`` filter from the query string.
     *         point_status: Optional ``status`` filter from the query string.
     *
     *     Returns:
     *         The paginated envelope, ordered by ``created_at ASC, id ASC``.
     */
    get: operations["list_points_api_v1_points_get"];
    put?: never;
    /**
     * Create Point
     * @description Register a point and its empty state projection.
     *
     *     Args:
     *         payload: The point to create.
     *         service: The point service for this request.
     *
     *     Returns:
     *         The created point, with HTTP 201.
     */
    post: operations["create_point_api_v1_points_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/points/{point_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Point
     * @description Read one point, archived ones included.
     *
     *     Args:
     *         point_id: Identifier of the point to read.
     *         service: The point service for this request.
     *
     *     Returns:
     *         The requested point.
     */
    get: operations["get_point_api_v1_points__point_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Point
     * @description Update a point's name, unit, range or status.
     *
     *     Args:
     *         point_id: Identifier of the point to update.
     *         payload: The fields to change.
     *         service: The point service for this request.
     *
     *     Returns:
     *         The updated point.
     */
    patch: operations["update_point_api_v1_points__point_id__patch"];
    trace?: never;
  };
  "/api/v1/points/{point_id}/state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Point State
     * @description Read the last known state of one point.
     *
     *     Until telemetry writes to it, the answer is the empty projection created
     *     with the point: no value, and ``quality = "no_data"``.
     *
     *     Args:
     *         point_id: Identifier of the point whose state to read.
     *         service: The point service for this request.
     *
     *     Returns:
     *         The point's current-state projection.
     */
    get: operations["get_point_state_api_v1_points__point_id__state_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/points/{point_id}/telemetry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Point Telemetry
     * @description Return a bounded, deterministic history for one logical point.
     */
    get: operations["list_point_telemetry_api_v1_points__point_id__telemetry_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/control-loops": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Control Loops
     * @description List configured loops, optionally restricted to one zone.
     *
     *     Args:
     *         service: The control-loop service for this request.
     *         params: The requested collection window.
     *         control_zone_id: Restricts the result to one zone when given.
     *
     *     Returns:
     *         One page of loops in the shared collection envelope.
     */
    get: operations["list_control_loops_api_v1_control_loops_get"];
    put?: never;
    /**
     * Create Control Loop
     * @description Configure the one hysteresis loop of a climate zone.
     *
     *     Args:
     *         payload: The loop to configure.
     *         service: The control-loop service for this request.
     *
     *     Returns:
     *         The created loop, with HTTP 201.
     */
    post: operations["create_control_loop_api_v1_control_loops_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/control-loops/{control_loop_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Control Loop
     * @description Read one control loop.
     *
     *     Args:
     *         control_loop_id: The loop to read.
     *         service: The control-loop service for this request.
     *
     *     Returns:
     *         The stored loop.
     */
    get: operations["get_control_loop_api_v1_control_loops__control_loop_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Commands
     * @description Return a bounded, deterministic newest-first window of commands.
     *
     *     Args:
     *         service: The command service for this request.
     *         control_loop_id: Restricts the result to one loop when given.
     *         trigger_sample_id: Restricts the result to one trigger when given.
     *         limit: Maximum number of commands to return.
     *
     *     Returns:
     *         The matching commands in ``created_at DESC, id DESC`` order.
     */
    get: operations["list_commands_api_v1_commands_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commands/{command_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Command
     * @description Read one command and the identifiers its chain is followed by.
     *
     *     Args:
     *         command_id: The command to read.
     *         service: The command service for this request.
     *
     *     Returns:
     *         The stored command.
     */
    get: operations["get_command_api_v1_commands__command_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/gateways": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Provision Gateway
     * @description Create a gateway or resolve an equivalent request by stable code.
     */
    post: operations["provision_gateway_api_v1_gateways_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/gateways/by-code/{code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Gateway By Code
     * @description Resolve a gateway by its stable provisioning code.
     */
    get: operations["get_gateway_by_code_api_v1_gateways_by_code__code__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/gateways/{gateway_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Gateway
     * @description Read a gateway by the UUID used by the Edge data plane.
     */
    get: operations["get_gateway_api_v1_gateways__gateway_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/gateways/{gateway_id}/configuration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Gateway Configuration
     * @description Read the gateway's normalized functional configuration.
     */
    get: operations["get_gateway_configuration_api_v1_gateways__gateway_id__configuration_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/gateways/{gateway_id}/points": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Gateway Points
     * @description Read the gateway's complete current logical-point authorization.
     */
    get: operations["get_gateway_points_api_v1_gateways__gateway_id__points_get"];
    put?: never;
    /**
     * Authorize Gateway Points
     * @description Add logical points without removing any existing authorization.
     */
    post: operations["authorize_gateway_points_api_v1_gateways__gateway_id__points_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/edge/telemetry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ingest Telemetry
     * @description Ingest one fully atomic telemetry envelope.
     */
    post: operations["ingest_telemetry_api_v1_edge_telemetry_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/edge/gateways/{gateway_id}/commands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Pending Commands
     * @description Poll pending commands scoped to one gateway.
     */
    get: operations["list_pending_commands_api_v1_edge_gateways__gateway_id__commands_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/edge/gateways/{gateway_id}/commands/{command_id}/acknowledgement": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Acknowledge Command
     * @description Store or replay a terminal command acknowledgement.
     */
    put: operations["acknowledge_command_api_v1_edge_gateways__gateway_id__commands__command_id__acknowledgement_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CommandListRead
     * @description A count-free collection of commands.
     *
     *     No total, like telemetry history and unlike the paged collections. The
     *     command list is a bounded newest-first window over an append-only table, and
     *     a ``COUNT(*)`` over it would grow with the history while answering a
     *     question nobody asked.
     */
    CommandListRead: {
      /** Items */
      items: components["schemas"]["CommandRead"][];
    };
    /**
     * CommandRead
     * @description One applied command, with every identifier its chain is followed by.
     *
     *     All three sample identifiers are returned rather than joined into embedded
     *     samples: the telemetry history endpoint already reads a sample, and
     *     duplicating it here would give one value two representations that could
     *     disagree.
     */
    CommandRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Idempotency Key */
      idempotency_key: string;
      /**
       * Control Loop Id
       * Format: uuid
       */
      control_loop_id: string;
      /**
       * Trigger Sample Id
       * Format: uuid
       */
      trigger_sample_id: string;
      /**
       * Target Point Id
       * Format: uuid
       */
      target_point_id: string;
      /**
       * Reported Point Id
       * Format: uuid
       */
      reported_point_id: string;
      /** Gateway Id */
      gateway_id: string | null;
      /** Desired Value */
      desired_value: boolean;
      state: components["schemas"]["CommandState"];
      /** Result Control Sample Id */
      result_control_sample_id: string | null;
      /** Result Status Sample Id */
      result_status_sample_id: string | null;
      /**
       * Issued At
       * Format: date-time
       */
      issued_at: string;
      /** Executed At */
      executed_at: string | null;
      /** Acknowledged At */
      acknowledged_at: string | null;
      /** Rejection Reason */
      rejection_reason: {
        [key: string]: string;
      } | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * CommandState
     * @description Delivery lifecycle of a logical command.
     * @enum {string}
     */
    CommandState: "pending" | "applied" | "rejected";
    /**
     * ConfigurationFacility
     * @description The facility the configuration document describes.
     */
    ConfigurationFacility: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Code */
      code: string;
      facility_type: components["schemas"]["FacilityType"];
      status: components["schemas"]["StatusEnum"];
    };
    /**
     * ConfigurationPoint
     * @description One point of the configuration document, with its current state.
     */
    ConfigurationPoint: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Code */
      code: string;
      /** Name */
      name: string;
      point_kind: components["schemas"]["PointKind"];
      /** Metric Type */
      metric_type: string;
      data_type: components["schemas"]["PointDataType"];
      /** Unit */
      unit: string | null;
      status: components["schemas"]["StatusEnum"];
      state: components["schemas"]["ConfigurationPointState"];
    };
    /**
     * ConfigurationPointState
     * @description The last known state of a point inside the configuration document.
     *
     *     A point that has received no telemetry reads ``value = null``,
     *     ``quality = "no_data"`` and ``observed_at = null``. ``received_at`` and
     *     ``revision`` are left to ``GET /api/v1/points/{point_id}/state``: the
     *     configuration answers "what is this growbox and what does it read", not "how
     *     did this value get here".
     */
    ConfigurationPointState: {
      /** Value */
      value?: unknown;
      quality: components["schemas"]["DataQuality"];
      /** Observed At */
      observed_at: string | null;
    };
    /**
     * ConfigurationSite
     * @description The site of a facility, as it appears in the configuration document.
     */
    ConfigurationSite: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Code */
      code: string;
      /** Timezone */
      timezone: string;
    };
    /**
     * ConfigurationZone
     * @description One control zone of the configuration document, with its composition.
     */
    ConfigurationZone: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Code */
      code: string;
      zone_type: components["schemas"]["ZoneType"];
      status: components["schemas"]["StatusEnum"];
      /** Points */
      points: components["schemas"]["ConfigurationZonePoint"][];
    };
    /**
     * ConfigurationZonePoint
     * @description One link inside a zone of the configuration document.
     *
     *     Only the link is described here. The point's own fields appear once, in the
     *     document's ``points`` list, so that a point taking part in three zones is
     *     still described once and cannot be described three inconsistent ways.
     */
    ConfigurationZonePoint: {
      /**
       * Point Id
       * Format: uuid
       */
      point_id: string;
      /** Code */
      code: string;
      role: components["schemas"]["ZonePointRole"];
    };
    /**
     * ControlLoopCreate
     * @description Body accepted by ``POST /api/v1/control-loops``.
     *
     *     Only the threshold ordering is checked here: both ends are always present
     *     in a creation body, so the rule needs nothing the schema cannot see. Every
     *     other rule needs the referenced zone and points and is applied by the
     *     service, which reports it with its own error code.
     */
    ControlLoopCreate: {
      /**
       * Control Zone Id
       * Format: uuid
       */
      control_zone_id: string;
      /**
       * Measurement Point Id
       * Format: uuid
       */
      measurement_point_id: string;
      /**
       * Control Point Id
       * Format: uuid
       */
      control_point_id: string;
      /**
       * Status Point Id
       * Format: uuid
       */
      status_point_id: string;
      /** Lower Threshold */
      lower_threshold: number | string;
      /** Upper Threshold */
      upper_threshold: number | string;
    };
    /**
     * ControlLoopRead
     * @description Representation returned by every control-loop endpoint.
     */
    ControlLoopRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Control Zone Id
       * Format: uuid
       */
      control_zone_id: string;
      /**
       * Measurement Point Id
       * Format: uuid
       */
      measurement_point_id: string;
      /**
       * Control Point Id
       * Format: uuid
       */
      control_point_id: string;
      /**
       * Status Point Id
       * Format: uuid
       */
      status_point_id: string;
      policy_type: components["schemas"]["ControlPolicyType"];
      /** Lower Threshold */
      lower_threshold: number;
      /** Upper Threshold */
      upper_threshold: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ControlPolicyType
     * @description Policy a control loop evaluates.
     *
     *     One member today. It is an enum rather than a constant string so that the
     *     stored value carries a ``CHECK`` constraint like every other enum column,
     *     and so a second policy arrives as a member instead of as a free-text value
     *     nothing validates.
     * @enum {string}
     */
    ControlPolicyType: "hysteresis-v1";
    /**
     * ControlZoneCreate
     * @description Body accepted by ``POST /api/v1/control-zones``.
     *
     *     There is no ``site_id``: a zone reaches its site through its facility, and
     *     accepting a second, redundant parent would make the two contradictable.
     */
    ControlZoneCreate: {
      /**
       * Facility Id
       * Format: uuid
       */
      facility_id: string;
      /** Name */
      name: string;
      /** Code */
      code: string;
      zone_type: components["schemas"]["ZoneType"];
    };
    /**
     * ControlZoneRead
     * @description Representation of a control zone returned by every zone endpoint.
     *
     *     No ``site_id`` is exposed. Clients that need the site read it from the
     *     zone's facility, which is the only place it is stored.
     */
    ControlZoneRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Facility Id
       * Format: uuid
       */
      facility_id: string;
      /** Name */
      name: string;
      /** Code */
      code: string;
      zone_type: components["schemas"]["ZoneType"];
      status: components["schemas"]["StatusEnum"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ControlZoneUpdate
     * @description Body accepted by ``PATCH /api/v1/control-zones/{zone_id}``.
     *
     *     Only the fields present in the request are applied, so an omitted field and
     *     an explicit ``null`` both leave the stored value untouched.
     *
     *     ``code`` and ``facility_id`` are declared even though neither can be
     *     changed. Accepting them here is what lets the service answer with HTTP 409
     *     ``immutable_field``, naming the refused field, instead of the generic HTTP
     *     422 that an unexpected field would produce.
     */
    ControlZoneUpdate: {
      /** Name */
      name?: string | null;
      zone_type?: components["schemas"]["ZoneType"] | null;
      status?: components["schemas"]["StatusEnum"] | null;
      /** Code */
      code?: string | null;
      /** Facility Id */
      facility_id?: string | null;
    };
    /**
     * DataQuality
     * @description Trustworthiness of a value, carried by the value rather than logged apart.
     *
     *     ``NO_DATA`` is the state every point starts in; the rest are the vocabulary
     *     telemetry writes with.
     * @enum {string}
     */
    DataQuality:
      | "no_data"
      | "good"
      | "uncertain"
      | "bad"
      | "stale"
      | "out_of_range"
      | "sensor_fault"
      | "simulated"
      | "manually_entered";
    /**
     * EdgeCommandAcknowledgement
     * @description Terminal acknowledgement resource identified by gateway and command.
     */
    EdgeCommandAcknowledgement: {
      /**
       * Contract Version
       * @constant
       */
      contract_version: "1.0";
      /**
       * Gateway Id
       * Format: uuid
       */
      gateway_id: string;
      /**
       * Command Id
       * Format: uuid
       */
      command_id: string;
      outcome: components["schemas"]["EdgeCommandOutcome"];
      /**
       * Acknowledged At
       * Format: date-time
       */
      acknowledged_at: string;
      /** Reason */
      reason?: components["schemas"]["EdgeRejectionReason"];
    };
    /**
     * EdgeCommandList
     * @description Pending commands visible to one gateway.
     */
    EdgeCommandList: {
      /**
       * Contract Version
       * @default 1.0
       * @constant
       */
      contract_version: "1.0";
      /**
       * Gateway Id
       * Format: uuid
       */
      gateway_id: string;
      /** Commands */
      commands: components["schemas"]["EdgePendingCommand"][];
    };
    /**
     * EdgeCommandOutcome
     * @description Terminal command outcomes.
     * @enum {string}
     */
    EdgeCommandOutcome: "applied" | "rejected";
    /**
     * EdgeErrorDetail
     * @description Safe field-level validation detail.
     */
    EdgeErrorDetail: {
      /** Location */
      location: (string | number)[];
      /** Message */
      message: string;
    };
    /**
     * EdgeErrorResponse
     * @description Error envelope published by contract v1.
     */
    EdgeErrorResponse: {
      /**
       * Contract Version
       * @default 1.0
       * @constant
       */
      contract_version: "1.0";
      error: components["schemas"]["EdgeErrorValue"];
    };
    /**
     * EdgeErrorValue
     * @description Public Edge error value.
     */
    EdgeErrorValue: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | "gateway_not_found"
        | "gateway_inactive"
        | "point_not_found"
        | "point_inactive"
        | "gateway_point_forbidden"
        | "telemetry_message_conflict"
        | "command_not_found"
        | "command_not_pending"
        | "command_acknowledgement_conflict"
        | "validation_error";
      /** Message */
      message: string;
      /** Details */
      details?: components["schemas"]["EdgeErrorDetail"][];
    };
    /**
     * EdgePendingCommand
     * @description One pending command in the exact public representation.
     */
    EdgePendingCommand: {
      /**
       * Command Id
       * Format: uuid
       */
      command_id: string;
      /**
       * Point Id
       * Format: uuid
       */
      point_id: string;
      /**
       * Reported Point Id
       * Format: uuid
       */
      reported_point_id: string;
      data_type: components["schemas"]["PointDataType"];
      /** Desired Value */
      desired_value: unknown;
      /**
       * Issued At
       * Format: date-time
       */
      issued_at: string;
      /**
       * State
       * @default pending
       * @constant
       */
      state: "pending";
    };
    /**
     * EdgeRejectionReason
     * @description Stable machine code and human explanation of a rejection.
     */
    EdgeRejectionReason: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /**
     * EdgeSourceKind
     * @description Kinds of producer represented by contract v1.
     * @enum {string}
     */
    EdgeSourceKind: "sensor" | "actuator" | "controller" | "operator" | "derived";
    /**
     * EdgeTelemetryEnvelope
     * @description One to 100 messages submitted by one gateway.
     */
    EdgeTelemetryEnvelope: {
      /**
       * Contract Version
       * @constant
       */
      contract_version: "1.0";
      /**
       * Gateway Id
       * Format: uuid
       */
      gateway_id: string;
      /**
       * Batch Id
       * Format: uuid
       */
      batch_id?: string;
      /** Messages */
      messages: components["schemas"]["EdgeTelemetryMessage"][];
    };
    /**
     * EdgeTelemetryIngestionResult
     * @description Ordered result for one telemetry envelope.
     */
    EdgeTelemetryIngestionResult: {
      /**
       * Contract Version
       * @default 1.0
       * @constant
       */
      contract_version: "1.0";
      /**
       * Gateway Id
       * Format: uuid
       */
      gateway_id: string;
      /**
       * Batch Id
       * Format: uuid
       */
      batch_id?: string;
      /** Results */
      results: components["schemas"]["EdgeTelemetryResultItem"][];
    };
    /**
     * EdgeTelemetryMessage
     * @description One producer-owned telemetry message.
     */
    EdgeTelemetryMessage: {
      /**
       * Message Id
       * Format: uuid
       */
      message_id: string;
      /**
       * Point Id
       * Format: uuid
       */
      point_id: string;
      data_type: components["schemas"]["PointDataType"];
      /** Value */
      value: unknown;
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string;
      quality: components["schemas"]["EdgeTelemetryQuality"];
      source: components["schemas"]["EdgeTelemetrySource"];
    };
    /**
     * EdgeTelemetryQuality
     * @description Submitted qualities; ``no_data`` is deliberately absent.
     * @enum {string}
     */
    EdgeTelemetryQuality:
      | "good"
      | "uncertain"
      | "bad"
      | "stale"
      | "out_of_range"
      | "sensor_fault"
      | "simulated"
      | "manually_entered";
    /**
     * EdgeTelemetryResultItem
     * @description Stored identity and outcome of one submitted message.
     */
    EdgeTelemetryResultItem: {
      /**
       * Message Id
       * Format: uuid
       */
      message_id: string;
      /**
       * Sample Id
       * Format: uuid
       */
      sample_id: string;
      outcome: components["schemas"]["TelemetryWriteOutcome"];
      /**
       * Received At
       * Format: date-time
       */
      received_at: string;
    };
    /**
     * EdgeTelemetrySource
     * @description Generic provenance metadata.
     */
    EdgeTelemetrySource: {
      kind: components["schemas"]["EdgeSourceKind"];
      /** Id */
      id: string;
    };
    /**
     * FacilityConfigurationRead
     * @description Response of ``GET /api/v1/facilities/{facility_id}/configuration``.
     *
     *     The whole growbox in one answer: what it is, where it stands, how it is
     *     divided into zones and which points those zones read and drive. It is a read
     *     model assembled from a fixed number of queries, not a serialised ORM graph —
     *     the entities keep referring to each other by identifier, and this document
     *     is where they are brought together.
     */
    FacilityConfigurationRead: {
      facility: components["schemas"]["ConfigurationFacility"];
      site: components["schemas"]["ConfigurationSite"];
      /** Control Zones */
      control_zones: components["schemas"]["ConfigurationZone"][];
      /** Points */
      points: components["schemas"]["ConfigurationPoint"][];
    };
    /**
     * FacilityCreate
     * @description Body accepted by ``POST /api/v1/facilities``.
     */
    FacilityCreate: {
      /**
       * Site Id
       * Format: uuid
       */
      site_id: string;
      /** Name */
      name: string;
      /** Code */
      code: string;
      facility_type: components["schemas"]["FacilityType"];
    };
    /**
     * FacilityRead
     * @description Representation of a facility returned by every facility endpoint.
     */
    FacilityRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Site Id
       * Format: uuid
       */
      site_id: string;
      /** Name */
      name: string;
      /** Code */
      code: string;
      facility_type: components["schemas"]["FacilityType"];
      status: components["schemas"]["StatusEnum"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * FacilityType
     * @description Kind of growing or infrastructure object a facility represents.
     * @enum {string}
     */
    FacilityType: "growbox" | "greenhouse" | "rack" | "seedling_room" | "utility";
    /**
     * FacilityUpdate
     * @description Body accepted by ``PATCH /api/v1/facilities/{facility_id}``.
     *
     *     Only the fields present in the request are applied, so an omitted field and
     *     an explicit ``null`` both leave the stored value untouched.
     *
     *     ``code`` and ``site_id`` are declared even though neither can be changed.
     *     Accepting them here is what lets the service answer with HTTP 409
     *     ``immutable_field``, naming the refused field, instead of the generic HTTP
     *     422 that an unexpected field would produce.
     */
    FacilityUpdate: {
      /** Name */
      name?: string | null;
      facility_type?: components["schemas"]["FacilityType"] | null;
      status?: components["schemas"]["StatusEnum"] | null;
      /** Code */
      code?: string | null;
      /** Site Id */
      site_id?: string | null;
    };
    /**
     * GatewayAuthorizedPointsRead
     * @description Normalized current point authorization for one gateway.
     */
    GatewayAuthorizedPointsRead: {
      /**
       * Gateway Id
       * Format: uuid
       */
      gateway_id: string;
      /** Point Ids */
      point_ids: string[];
    };
    /**
     * GatewayConfigurationRead
     * @description Normalized fields that define a gateway's functional configuration.
     */
    GatewayConfigurationRead: {
      /**
       * Gateway Id
       * Format: uuid
       */
      gateway_id: string;
      /** Code */
      code: string;
      /**
       * Site Id
       * Format: uuid
       */
      site_id: string;
    };
    /**
     * GatewayCreate
     * @description Configuration accepted by the idempotent gateway provisioning operation.
     */
    GatewayCreate: {
      /** Code */
      code: string;
      /**
       * Site Id
       * Format: uuid
       */
      site_id: string;
    };
    /**
     * GatewayErrorResponse
     * @description Documented management-plane error response.
     */
    GatewayErrorResponse: {
      error: components["schemas"]["GatewayErrorValue"];
    };
    /**
     * GatewayErrorValue
     * @description One stable error in the common API envelope.
     */
    GatewayErrorValue: {
      /** Code */
      code: string;
      /** Message */
      message: string;
      /** Details */
      details: {
        [key: string]: unknown;
      };
    };
    /**
     * GatewayPointAuthorizationOutcome
     * @description Effect of one requested point authorization.
     * @enum {string}
     */
    GatewayPointAuthorizationOutcome: "authorized" | "already_authorized";
    /**
     * GatewayPointAuthorizationRead
     * @description Outcome for one distinct point in an additive authorization request.
     */
    GatewayPointAuthorizationRead: {
      /**
       * Point Id
       * Format: uuid
       */
      point_id: string;
      outcome: components["schemas"]["GatewayPointAuthorizationOutcome"];
    };
    /**
     * GatewayPointAuthorizationRequest
     * @description Points to add to a gateway's authorization set.
     */
    GatewayPointAuthorizationRequest: {
      /** Point Ids */
      point_ids: string[];
    };
    /**
     * GatewayPointAuthorizationResult
     * @description Result of applying an additive point-authorization request.
     */
    GatewayPointAuthorizationResult: {
      /**
       * Gateway Id
       * Format: uuid
       */
      gateway_id: string;
      /** Points */
      points: components["schemas"]["GatewayPointAuthorizationRead"][];
    };
    /**
     * GatewayProvisioningOutcome
     * @description Whether an idempotent provisioning request created or resolved a gateway.
     * @enum {string}
     */
    GatewayProvisioningOutcome: "created" | "existing";
    /**
     * GatewayProvisioningRead
     * @description Result of create-or-resolve gateway provisioning.
     */
    GatewayProvisioningRead: {
      outcome: components["schemas"]["GatewayProvisioningOutcome"];
      gateway: components["schemas"]["GatewayRead"];
      configuration: components["schemas"]["GatewayConfigurationRead"];
    };
    /**
     * GatewayRead
     * @description Administrative representation of one gateway resource.
     */
    GatewayRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Code */
      code: string;
      /**
       * Site Id
       * Format: uuid
       */
      site_id: string;
      status: components["schemas"]["StatusEnum"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "unavailable";
      /** Service */
      service: string;
      /**
       * Database
       * @enum {string}
       */
      database: "ok" | "unavailable";
    };
    /** Page[ControlLoopRead] */
    Page_ControlLoopRead_: {
      /** Items */
      items: components["schemas"]["ControlLoopRead"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** Page[ControlZoneRead] */
    Page_ControlZoneRead_: {
      /** Items */
      items: components["schemas"]["ControlZoneRead"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** Page[FacilityRead] */
    Page_FacilityRead_: {
      /** Items */
      items: components["schemas"]["FacilityRead"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** Page[PointRead] */
    Page_PointRead_: {
      /** Items */
      items: components["schemas"]["PointRead"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** Page[SiteRead] */
    Page_SiteRead_: {
      /** Items */
      items: components["schemas"]["SiteRead"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** Page[ZonePointAssignmentRead] */
    Page_ZonePointAssignmentRead_: {
      /** Items */
      items: components["schemas"]["ZonePointAssignmentRead"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /**
     * PointCreate
     * @description Body accepted by ``POST /api/v1/points``.
     *
     *     The relationship between ``data_type``, ``unit`` and the range is not
     *     checked here. Those rules produce their own error codes —
     *     ``unit_not_allowed``, ``range_not_allowed`` — which a schema validator
     *     cannot express, so the service applies them. The one rule kept at this level
     *     is the ordering of the range, because both ends are always visible in a
     *     creation body.
     */
    PointCreate: {
      /**
       * Site Id
       * Format: uuid
       */
      site_id: string;
      /** Facility Id */
      facility_id?: string | null;
      /** Code */
      code: string;
      /** Name */
      name: string;
      point_kind: components["schemas"]["PointKind"];
      /** Metric Type */
      metric_type: string;
      data_type: components["schemas"]["PointDataType"];
      /** Unit */
      unit?: string | null;
      /** Min Value */
      min_value?: number | string | null;
      /** Max Value */
      max_value?: number | string | null;
    };
    /**
     * PointDataType
     * @description Type of the values a point carries.
     *
     *     Governs how :attr:`PointCurrentState.value` is interpreted, which is why
     *     one ``jsonb`` column can serve numeric, boolean and textual points without
     *     a table per type.
     * @enum {string}
     */
    PointDataType: "float" | "integer" | "boolean" | "string";
    /**
     * PointKind
     * @description Role a point plays in the system.
     *
     *     One table with this column, rather than separate tables per kind: a
     *     measurement and a control point differ in how they are used, not in what
     *     they are, and every rule that refers to points has to span all four.
     * @enum {string}
     */
    PointKind: "measurement" | "control" | "status" | "derived";
    /**
     * PointRead
     * @description Representation of a point returned by every point endpoint.
     *
     *     Carries no value and no physical address. Both omissions are the point of
     *     the entity: the value lives in :class:`PointStateRead`, and the hardware
     *     behind it can arrive later without this representation changing.
     */
    PointRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Site Id
       * Format: uuid
       */
      site_id: string;
      /** Facility Id */
      facility_id: string | null;
      /** Code */
      code: string;
      /** Name */
      name: string;
      point_kind: components["schemas"]["PointKind"];
      /** Metric Type */
      metric_type: string;
      data_type: components["schemas"]["PointDataType"];
      /** Unit */
      unit: string | null;
      /** Min Value */
      min_value: number | null;
      /** Max Value */
      max_value: number | null;
      status: components["schemas"]["StatusEnum"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * PointStateRead
     * @description Representation returned by ``GET /api/v1/points/{point_id}/state``.
     *
     *     A point that has received no telemetry answers with ``value = null`` and
     *     ``quality = "no_data"``. No endpoint writes this projection: it is filled
     *     only through the telemetry write boundary.
     */
    PointStateRead: {
      /**
       * Point Id
       * Format: uuid
       */
      point_id: string;
      /** Value */
      value?: unknown;
      /** Observed At */
      observed_at: string | null;
      /** Received At */
      received_at: string | null;
      quality: components["schemas"]["DataQuality"];
      /** Revision */
      revision: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * PointUpdate
     * @description Body accepted by ``PATCH /api/v1/points/{point_id}``.
     *
     *     Only the fields present in the request are applied. Unlike the topology
     *     schemas, an explicit ``null`` is *not* the same as omitting a field here:
     *     ``unit``, ``min_value`` and ``max_value`` are nullable columns, so sending
     *     ``{"min_value": null}`` clears the lower bound while leaving it out keeps
     *     it. The service reads ``model_fields_set`` to tell the two apart.
     *
     *     Every field the point's meaning depends on is declared even though none can
     *     be changed, and declared with a permissive type on purpose. Accepting
     *     ``{"point_kind": "vibes"}`` as a string is what lets the service answer with
     *     HTTP 409 ``immutable_field`` — the honest reason for the refusal — instead
     *     of the HTTP 422 an enum would produce for a value that was never going to be
     *     applied anyway.
     */
    PointUpdate: {
      /** Name */
      name?: string | null;
      /** Unit */
      unit?: string | null;
      /** Min Value */
      min_value?: number | string | null;
      /** Max Value */
      max_value?: number | string | null;
      status?: components["schemas"]["StatusEnum"] | null;
      /** Code */
      code?: string | null;
      /** Site Id */
      site_id?: string | null;
      /** Facility Id */
      facility_id?: string | null;
      /** Point Kind */
      point_kind?: string | null;
      /** Metric Type */
      metric_type?: string | null;
      /** Data Type */
      data_type?: string | null;
    };
    /**
     * SiteCreate
     * @description Body accepted by ``POST /api/v1/sites``.
     */
    SiteCreate: {
      /** Name */
      name: string;
      /** Code */
      code: string;
      /**
       * Timezone
       * @default UTC
       */
      timezone: string;
    };
    /**
     * SiteRead
     * @description Representation of a site returned by every site endpoint.
     */
    SiteRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Code */
      code: string;
      /** Timezone */
      timezone: string;
      status: components["schemas"]["StatusEnum"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * SiteUpdate
     * @description Body accepted by ``PATCH /api/v1/sites/{site_id}``.
     *
     *     Only the fields present in the request are applied, so an omitted field and
     *     an explicit ``null`` both leave the stored value untouched.
     *
     *     ``code`` is declared even though it cannot be changed. Accepting it here is
     *     what lets the service answer with HTTP 409 ``immutable_field`` instead of
     *     the generic HTTP 422 that an unexpected field would produce.
     */
    SiteUpdate: {
      /** Name */
      name?: string | null;
      /** Timezone */
      timezone?: string | null;
      status?: components["schemas"]["StatusEnum"] | null;
      /** Code */
      code?: string | null;
    };
    /**
     * StatusEnum
     * @description Lifecycle of an entity. Rows are archived instead of being deleted.
     * @enum {string}
     */
    StatusEnum: "active" | "archived";
    /**
     * TelemetryHistoryRead
     * @description A count-free collection of telemetry samples.
     */
    TelemetryHistoryRead: {
      /** Items */
      items: components["schemas"]["TelemetrySampleRead"][];
    };
    /**
     * TelemetrySampleRead
     * @description One stored measurement returned unchanged by the history API.
     */
    TelemetrySampleRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Point Id
       * Format: uuid
       */
      point_id: string;
      /** Value */
      value: unknown;
      /** Unit */
      unit: string | null;
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string;
      /**
       * Received At
       * Format: date-time
       */
      received_at: string;
      quality: components["schemas"]["DataQuality"];
    };
    /**
     * TelemetryWriteOutcome
     * @description What the write boundary did with an offered sample.
     *
     *     A producer used to be told nothing: the sample was accepted either way, and
     *     "accepted" covered three different things. Automation needs them apart,
     *     because only the first one is new information about the point — a replay and
     *     a late arrival describe a state the system has already reacted to, and
     *     re-deciding on either would act twice on one measurement.
     *
     *     Attributes:
     *         RECORDED_CURRENT: The sample was new and became the current state.
     *         DUPLICATE: The identifier was already recorded; nothing changed.
     *         OUT_OF_ORDER: The sample was recorded in history, but an equal or newer
     *             measurement already holds the current state.
     * @enum {string}
     */
    TelemetryWriteOutcome: "recorded_current" | "duplicate" | "out_of_order";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * ZonePointAssignmentCreate
     * @description Body accepted by ``POST /api/v1/control-zones/{zone_id}/points``.
     *
     *     There is no ``control_zone_id``: the zone comes from the path, and
     *     accepting a second, contradictable copy of it in the body would only create
     *     a way for the two to disagree.
     */
    ZonePointAssignmentCreate: {
      /**
       * Point Id
       * Format: uuid
       */
      point_id: string;
      role: components["schemas"]["ZonePointRole"];
    };
    /**
     * ZonePointAssignmentRead
     * @description Representation of one zone-point assignment.
     *
     *     The point's own fields are copied in rather than referenced, because a
     *     client listing a zone's composition wants to read it without a request per
     *     link. The copy is deliberately partial: what a point *means* is answered by
     *     ``GET /api/v1/points/{point_id}``, and duplicating the whole entity here
     *     would make this endpoint a second, competing source of it.
     */
    ZonePointAssignmentRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Control Zone Id
       * Format: uuid
       */
      control_zone_id: string;
      /**
       * Point Id
       * Format: uuid
       */
      point_id: string;
      role: components["schemas"]["ZonePointRole"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Point Code */
      point_code: string;
      /** Point Name */
      point_name: string;
      point_kind: components["schemas"]["PointKind"];
      data_type: components["schemas"]["PointDataType"];
      /** Unit */
      unit: string | null;
    };
    /**
     * ZonePointRole
     * @description Part a point plays inside the zone it is assigned to.
     *
     *     The role is a property of the *link*, not of the point: the same air
     *     temperature point can be the primary measurement of a climate zone and a
     *     safety interlock of a safety zone at the same time.
     * @enum {string}
     */
    ZonePointRole:
      | "primary_measurement"
      | "secondary_measurement"
      | "control_output"
      | "status_feedback"
      | "safety_interlock"
      | "derived_indicator";
    /**
     * ZoneType
     * @description Aspect of a facility a control zone measures or controls.
     * @enum {string}
     */
    ZoneType:
      "climate" | "irrigation" | "lighting" | "measurement" | "nutrient_solution" | "safety";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  list_sites_api_v1_sites_get: {
    parameters: {
      query?: {
        /** @description Restrict the result to one lifecycle state. */
        status?: components["schemas"]["StatusEnum"] | null;
        /** @description Number of items to return, between 1 and 200. */
        limit?: number;
        /** @description Number of items to skip. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_SiteRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_site_api_v1_sites_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SiteCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_site_api_v1_sites__site_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        site_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_site_api_v1_sites__site_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        site_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SiteUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_facilities_api_v1_facilities_get: {
    parameters: {
      query?: {
        /** @description Restrict the result to the facilities of one site. */
        site_id?: string | null;
        /** @description Restrict the result to one kind of facility. */
        facility_type?: components["schemas"]["FacilityType"] | null;
        /** @description Restrict the result to one lifecycle state. */
        status?: components["schemas"]["StatusEnum"] | null;
        /** @description Number of items to return, between 1 and 200. */
        limit?: number;
        /** @description Number of items to skip. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_FacilityRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_facility_api_v1_facilities_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FacilityCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FacilityRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_facility_api_v1_facilities__facility_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        facility_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FacilityRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_facility_api_v1_facilities__facility_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        facility_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FacilityUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FacilityRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_facility_configuration_api_v1_facilities__facility_id__configuration_get: {
    parameters: {
      query?: {
        /** @description Include archived zones and points in the document. */
        include_archived?: boolean;
      };
      header?: never;
      path: {
        facility_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FacilityConfigurationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_control_zones_api_v1_control_zones_get: {
    parameters: {
      query?: {
        /** @description Restrict the result to the zones of one facility. */
        facility_id?: string | null;
        /** @description Restrict the result to one kind of zone. */
        zone_type?: components["schemas"]["ZoneType"] | null;
        /** @description Restrict the result to one lifecycle state. */
        status?: components["schemas"]["StatusEnum"] | null;
        /** @description Number of items to return, between 1 and 200. */
        limit?: number;
        /** @description Number of items to skip. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_ControlZoneRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_control_zone_api_v1_control_zones_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ControlZoneCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ControlZoneRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_control_zone_api_v1_control_zones__zone_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ControlZoneRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_control_zone_api_v1_control_zones__zone_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ControlZoneUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ControlZoneRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_zone_point_assignments_api_v1_control_zones__zone_id__points_get: {
    parameters: {
      query?: {
        /** @description Number of items to return, between 1 and 200. */
        limit?: number;
        /** @description Number of items to skip. */
        offset?: number;
      };
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_ZonePointAssignmentRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_zone_point_assignment_api_v1_control_zones__zone_id__points_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ZonePointAssignmentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ZonePointAssignmentRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_zone_point_assignment_api_v1_control_zones__zone_id__points__assignment_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        zone_id: string;
        assignment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_points_api_v1_points_get: {
    parameters: {
      query?: {
        /** @description Restrict the result to the points of one site. */
        site_id?: string | null;
        /** @description Restrict the result to the points of one facility. */
        facility_id?: string | null;
        /** @description Restrict the result to one role of point. */
        point_kind?: components["schemas"]["PointKind"] | null;
        /** @description Restrict the result to one measured quantity. */
        metric_type?: string | null;
        /** @description Restrict the result to one lifecycle state. */
        status?: components["schemas"]["StatusEnum"] | null;
        /** @description Number of items to return, between 1 and 200. */
        limit?: number;
        /** @description Number of items to skip. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_PointRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_point_api_v1_points_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PointCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PointRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_point_api_v1_points__point_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        point_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PointRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_point_api_v1_points__point_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        point_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PointUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PointRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_point_state_api_v1_points__point_id__state_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        point_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PointStateRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_point_telemetry_api_v1_points__point_id__telemetry_get: {
    parameters: {
      query?: {
        /** @description Inclusive lower bound on observed_at. */
        from?: string | null;
        /** @description Inclusive upper bound on observed_at. */
        to?: string | null;
        /** @description Maximum number of samples to return. */
        limit?: number;
      };
      header?: never;
      path: {
        point_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TelemetryHistoryRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_control_loops_api_v1_control_loops_get: {
    parameters: {
      query?: {
        control_zone_id?: string | null;
        /** @description Number of items to return, between 1 and 200. */
        limit?: number;
        /** @description Number of items to skip. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_ControlLoopRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_control_loop_api_v1_control_loops_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ControlLoopCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ControlLoopRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_control_loop_api_v1_control_loops__control_loop_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        control_loop_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ControlLoopRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_commands_api_v1_commands_get: {
    parameters: {
      query?: {
        /** @description Restrict the result to the commands of one control loop. */
        control_loop_id?: string | null;
        /** @description Restrict the result to the commands one measurement caused. */
        trigger_sample_id?: string | null;
        /** @description Maximum number of commands to return. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommandListRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_command_api_v1_commands__command_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        command_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommandRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  provision_gateway_api_v1_gateways_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GatewayCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayProvisioningRead"];
        };
      };
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayProvisioningRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
    };
  };
  get_gateway_by_code_api_v1_gateways_by_code__code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
    };
  };
  get_gateway_api_v1_gateways__gateway_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        gateway_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
    };
  };
  get_gateway_configuration_api_v1_gateways__gateway_id__configuration_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        gateway_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayConfigurationRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
    };
  };
  get_gateway_points_api_v1_gateways__gateway_id__points_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        gateway_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayAuthorizedPointsRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
    };
  };
  authorize_gateway_points_api_v1_gateways__gateway_id__points_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        gateway_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GatewayPointAuthorizationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayPointAuthorizationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayErrorResponse"];
        };
      };
    };
  };
  ingest_telemetry_api_v1_edge_telemetry_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EdgeTelemetryEnvelope"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeTelemetryIngestionResult"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
    };
  };
  list_pending_commands_api_v1_edge_gateways__gateway_id__commands_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path: {
        gateway_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeCommandList"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
    };
  };
  acknowledge_command_api_v1_edge_gateways__gateway_id__commands__command_id__acknowledgement_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        gateway_id: string;
        command_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EdgeCommandAcknowledgement"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeCommandAcknowledgement"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeErrorResponse"];
        };
      };
    };
  };
}
